### PR TITLE
Project: Design & UX

### PR DESCRIPTION
**Pull request by krys2fa**
Milestones:

-- aligned elements using float, flex or grid.
-- used article tags for articles on the page.
.
The goal was to make a grayscale heatmap of the Smashing Magazine webpage.

### CODE REVIEW

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👋

**Review by mikenath223 — APPROVED** [review]
### Hi Team 👋

You've done quite well on this @krys2fa  and @ozovalihasan  👌

### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

HAPPY CODING👨‍💻

**Comment by ozovalihasan** [comment]
Thank you :tada:

**Comment by krys2fa** [comment]
Thanks for the review and approval @mikenath223

**Pull request merged**
